### ISSUE TITLE
copyright

### ISSUE THREAD

**Issue by tkphd** [usnistgov/pyPRISM#11]
You cannot simultaneously dedicate a work to the public domain (NIST license it) and reserve copyrights. Please remove the following text from LICENSE:
> Copyright (c) 2017 Tyler B. Martin, Ph.D.

**Comment by martintb** [comment]
So, I'll remove the language the from the LICENSE on the next dev merge to master, but I question your reasoning. 

NIST's [licensing page](https://www.nist.gov/director/licensing) only asks that we include the specific licensing statement but makes no requests beyond this. The default template for the [MIT license](https://opensource.org/licenses/MIT) includes the copyright line. The wiki page [Public Copyright Licensing](https://en.wikipedia.org/wiki/Public_copyright_license) also indicates that there is a copyright holder who grants public access to the software. I could see that we, as NIST employees, don't have the right to grant copyright, but that should only mean that my name should be replaced by NIST's. 

Could you point me to the NIST or general resource which explains your request? I am not looking to be combative, just looking to see your reasoning. Thanks!

**Comment by tkphd** [comment]
Hey @martintb,

No problem, I don't mind clarifying. I am not a lawyer, but my reasoning is as follows:

1. The MIT license is a *bona fide* license, mixing an assertion of copy rights with a legally enforceable statement of what the licensee has your permission to do with whatever copies they make. Consider it a distribution with "some rights reserved."
2. The NIST "License" is a dedication to the public domain, roughly equivalent to [CC0](https://wiki.creativecommons.org/wiki/CC0_FAQ). The text of the dedication itself waives copyright, as we are required to do by law. The suspect line, `Copyright (c) 2017 Tyler B. Martin, Ph.D.`, tells the reader (or licensee) that you have personally reserved copyrights. This is a contradiction: you can't mix a *waiver* of copyrights with a set of restrictions, and under 17USC105, you have no rights to reserve in the first place.
3. Per [NIST's licensing page](https://www.nist.gov/director/licensing), only Standard Reference Data is subject to copyright, hence the inclusion of 
    > Copyright © 2013 by the U.S. Secretary of Commerce on behalf of the United States of America. All    rights reserved.

    None of the other "licenses" include a copyright statement, and it is no accident.

I hope that clarifies.

**Comment by tkphd** [comment]
By the way, this came up because [your repository looks awesome](https://github.com/usnistgov/awesome-nist/issues/1)  :+1:

**Comment by martintb** [comment]
Thanks Trevor! I did not appreciate the difference between CC0 and MIT and I was under the mistaken impression that MIT was a pubic domain license. MIT is highly permissive but not public domain. In addition to your comment I found this [infographic](https://qph.fs.quoracdn.net/main-qimg-f74b34efd2c3ef9297094e134d0d9793-c) helpful.

Interestingly, this page on [CC0](https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F) has a similar "name line" but replaced "copyright" with "written by". This has no bearing on the NIST license, just a general observation. 

Regardless, I've fixed the LICENSE on the dev branch and will merge to master in the next few weeks. Thank you for the helpful suggestions! Let me know if there are other things I should work on to clean up my repo.

**Comment by tkphd** [comment]
Helpful infographic, thanks for digging it up! Looks like a [CC BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/2.0/) work, so here's the [original source](https://pt.slideshare.net/cibbva/infographic-what-are-open-source-license-english) from BBVA Open Innovation Madrid :wink:
