### ISSUE TITLE
Incorrect freely jointed chain limit in Discrete Koyama Model 

### ISSUE THREAD

**Issue by rjadrich** [usnistgov/pyPRISM#14]
The exact limit of a freely jointed chain in the Discrete Koyama Omega contains a small error. There are two problems that I have identified:

1. The limit of freely jointed is not when the persistence length (lp) -> 4/3 but rather it depends on both the bond length (l) and the site diameter (sigma). 
2. The average cosine quantities are also incorrect in the same limit.

I have a fix for everything that I will issue a pull request for if so desired.

**Comment by martintb** [comment]
A PR would be fantastic! If possible, in the PR could you include a _brief_ explanation and reference(s) which backs up your fix. I'm not looking for a dissertation but rather just something to explain your reasoning even if it's just an equation number in a paper and a few sentences. FYI, we used http://dx.doi.org/10.1021/ma00216a018 when developing this omega. 

I'll need a bit of time to evaluate the error and your proposed fix but, assuming your fix looks good and doesn't break any of our tests, we'll merge to dev and include the fix in the next release. Thanks!

**Comment by rjadrich** [comment]
Sure thing. I will share supporting information regarding the issue and fix. The fix is kind of subtle and involves an analysis of the limiting behavior of the model in the ref you provided (this is what I am working from as well). I will document the math in a document and via my Mathematica workbook (it is short). I will try to finish it tonight.

**Comment by martintb** [comment]
Fixed with merged PR #15
