### ISSUE TITLE
Accessing PRISM object internals

### ISSUE THREAD

**Issue by tgartner** [usnistgov/pyPRISM#5]
It would be good to update the API docs, FAQ, and tutorial with an example of how to access classes within a PRISM object that do not explicitly have their own pre-written compute module. E.g. how to access the direct correlation function from a solved PRISM object (C_AA = PRISM.directCorr['A','A'])

**Comment by martintb** [comment]
This request has been achieved with the new tutorial notebook. A static version of the tutorial notebook can be viewed in the [documentation](http://pyprism.readthedocs.io/en/latest/tutorial/NB8.pyPRISM.Internals.html) 

I am not sure if adding more information elsewhere at this point would be helpful. Closing this issue for now.
